// HULK Parser
import type { Token, ASTNode, NumberNode, StringNode, BooleanNode, IdentifierNode, BinaryNode, UnaryNode, CallNode, FunctionNode, LetNode, IfNode, Binding } from './types';
import { SyntaxError } from './errors';

export class Parser {
  private t: Token[] = []; private p: number = 0;
  constructor(tokens: Token[]) { this.t = tokens; }
  parse(): ASTNode { const c = this.cur(); if (c.type === 'KEYWORD') { if (c.value === 'function') return this.fun(); if (c.value === 'let') return this.let(); if (c.value === 'if') return this.ife(); } return this.e(); }
  private cur(): Token { return this.t[this.p] ?? { type: 'EOF', value: '', line: 1, column: 0 }; }
  private adv(): Token { return this.t[this.p++] ?? { type: 'EOF', value: '', line: 1, column: 0 }; }
  private kw(v: string): boolean { return this.cur().type === 'KEYWORD' && this.cur().value === v; }
  private want(type: string): Token { const c = this.cur(); if (c.type !== type) throw new SyntaxError(`want ${type} got '${c.value}'`); return this.adv(); }
  private fun(): ASTNode { this.adv(); const name = this.want('IDENTIFIER').value as string; this.want('LPAREN'); const P: string[] = []; if (this.cur().type !== 'RPAREN') { P.push(this.want('IDENTIFIER').value as string); while (this.cur().type === 'COMMA') { this.adv(); P.push(this.want('IDENTIFIER').value as string); } } this.want('RPAREN'); this.want('ARROW'); const body = this.parseFull(); if (this.cur().type === 'SEMICOLON') this.adv(); return { type: 'Function', name, params: P, body } as FunctionNode; }
  private let(): ASTNode { this.adv(); const B: Binding[] = []; const name = this.want('IDENTIFIER').value as string; this.want('EQUAL'); const val = this.parseFull(); B.push({ name, value: val }); while (this.cur().type === 'COMMA') { this.adv(); const bn = this.want('IDENTIFIER').value as string; this.want('EQUAL'); const bv = this.parseFull(); B.push({ name: bn, value: bv }); } this.want('KEYWORD'); const body = this.parseFull(); return { type: 'Let', bindings: B, body } as LetNode; }
  private parseFull(): ASTNode { const c = this.cur(); if (c.type === 'KEYWORD' && c.value === 'if') return this.ife(); return this.e(); }
  private ife(): ASTNode { this.adv(); this.want('LPAREN'); const cond = this.parseFull(); this.want('RPAREN'); const th = this.parseFull(); this.want('KEYWORD'); const el = this.parseFull(); return { type: 'If', condition: cond, then: th, else: el } as IfNode; }
  private e(): ASTNode { let l = this.t2(); const c = this.cur(); if (c.type === 'EQ' || c.type === 'NE' || c.type === 'LT' || c.type === 'LE' || c.type === 'GT' || c.type === 'GE') { this.adv(); const r = this.t2(); return { type: 'Binary', op: c.value as string, left: l, right: r } as BinaryNode; } return l; }
  private t2(): ASTNode { let l = this.t3(); while (this.cur().type === 'PLUS' || this.cur().type === 'MINUS' || this.cur().type === 'AT') { const op = this.adv().value as string; const r = this.t3(); l = { type: 'Binary', op, left: l, right: r } as BinaryNode; } return l; }
  private t3(): ASTNode { let l = this.t4(); while (this.cur().type === 'STAR' || this.cur().type === 'SLASH' || this.cur().type === 'PERCENT') { const op = this.adv().value as string; const r = this.t4(); l = { type: 'Binary', op, left: l, right: r } as BinaryNode; } return l; }
  private t4(): ASTNode { if (this.cur().type === 'MINUS') { this.adv(); return { type: 'Unary', op: '-', operand: this.t4() } as UnaryNode; } let l = this.t5(); if (this.cur().type === 'CARET') { this.adv(); const r = this.t4(); return { type: 'Binary', op: '^', left: l, right: r } as BinaryNode; } return l; }
  private t5(): ASTNode { let l = this.atom(); if (this.cur().type === 'LPAREN' && l.type === 'Identifier') { const name = l.name; this.adv(); const A: ASTNode[] = []; if (this.cur().type !== 'RPAREN') { A.push(this.e()); while (this.cur().type === 'COMMA') { this.adv(); A.push(this.e()); } } this.want('RPAREN'); return { type: 'Call', name, args: A } as CallNode; } return l; }
  private atom(): ASTNode { const c = this.cur(); if (c.type === 'NUMBER') { this.adv(); return { type: 'Number', value: c.value as number } as NumberNode; } if (c.type === 'STRING') { this.adv(); return { type: 'String', value: c.value as string } as StringNode; } if (this.kw('true') || this.kw('false')) { this.adv(); return { type: 'Boolean', value: c.value === 'true' } as BooleanNode; } if (this.kw('PI') || this.kw('E')) { this.adv(); return { type: 'Identifier', name: c.value as string } as IdentifierNode; } if (c.type === 'KEYWORD' && !this.kw('let') && !this.kw('in') && !this.kw('else') && !this.kw('if')) { this.adv(); return { type: 'Identifier', name: c.value as string } as IdentifierNode; } if (c.type === 'IDENTIFIER') { this.adv(); return { type: 'Identifier', name: c.value as string } as IdentifierNode; } if (c.type === 'LPAREN') { this.adv(); const x = this.e(); this.want('RPAREN'); return x; } throw new SyntaxError(`bad ${c.value}`); }
}
export function parse(tokens: Token[]): ASTNode { return new Parser(tokens).parse(); }